name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v4.2.2

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3.5.0

      - name: setup jdk 17
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 17
          distribution: "microsoft"
          cache: "gradle"

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew shadowJar

      - name: capture build artifacts
        uses: actions/upload-artifact@v4.5.0
        with:
          name: Artifacts
          path: build/libs/
